export const PATHS = {
    SIGNIN: '/',
    SIGNUP: '/signup',
    WELCOME: '/welcome',
    PROFILE: '/profile',
    CREATE_PACKAGE: '/profile/create-package',
    PACKAGE_LIST: '/profile/packages-list',
    EDIT_PACKAGE: '/profile/edit-package',
    PACKAGE_DITAILS: '/profile/package-details/:packageId',
    CREATE_DRAW: '/profile/create-draw',
    DRAW_LIST: '/profile/draw-list',
    DRAW_DETAILS: '/profile/draw-details/:drawId',
    DRAW_INFO: '/draw-info/:drawId',
    PACKAGE_INFO: '/package-info/:packageId',
    TOTAL: '/total',
    DRAW_PAYMENT: '/payment/:status',
    PACKAGE_PAYMENT: '/payment/membership/:status',
    GOOGLE: '/google/success',
    OTP: '/otp',
    DRAW_USERS: '/draw-memberships/:drawId',
    PACKAGE_USERS: '/package-memberships/:packageId',
    STRIPE: '/stripe-account/:status',
    PRIVACY: '/privacy-policy',
    RESET_PASS: '/forgot-password/:email',
    CUSTOMER_VERIFICATION: '/verify-customer',
    CUSTOMER_PORTAL: '/customer-portal',
    CUSTOMER_SIGNIN: '/customer-signin'
};
